// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chat.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.example.aaaaaac.proto.Chat

@kotlin.jvm.JvmName("-initializeaudioMsg")
public inline fun audioMsg(block: AudioMsgKt.Dsl.() -> kotlin.Unit): Chat.AudioMsg =
  AudioMsgKt.Dsl._create(Chat.AudioMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `AudioMsg`
 */
public object AudioMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Chat.AudioMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Chat.AudioMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Chat.AudioMsg = _builder.build()

    /**
     * `string filename = 1;`
     */
    public var filename: kotlin.String
      @JvmName("getFilename")
      get() = _builder.getFilename()
      @JvmName("setFilename")
      set(value) {
        _builder.setFilename(value)
      }
    /**
     * `string filename = 1;`
     */
    public fun clearFilename() {
      _builder.clearFilename()
    }

    /**
     * `fixed32 length = 2;`
     */
    public var length: kotlin.Int
      @JvmName("getLength")
      get() = _builder.getLength()
      @JvmName("setLength")
      set(value) {
        _builder.setLength(value)
      }
    /**
     * `fixed32 length = 2;`
     */
    public fun clearLength() {
      _builder.clearLength()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated bytes data = 3;`
     */
     public val data: com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDataList()
      )
    /**
     * `repeated bytes data = 3;`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addData")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.add(value: com.google.protobuf.ByteString) {
      _builder.addData(value)
    }/**
     * `repeated bytes data = 3;`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.plusAssign(value: com.google.protobuf.ByteString) {
      add(value)
    }/**
     * `repeated bytes data = 3;`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllData")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      _builder.addAllData(values)
    }/**
     * `repeated bytes data = 3;`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      addAll(values)
    }/**
     * `repeated bytes data = 3;`
     * @param index The index to set the value at.
     * @param value The data to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setData")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.set(index: kotlin.Int, value: com.google.protobuf.ByteString) {
      _builder.setData(index, value)
    }/**
     * `repeated bytes data = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearData")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, DataProxy>.clear() {
      _builder.clearData()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun Chat.AudioMsg.copy(block: AudioMsgKt.Dsl.() -> kotlin.Unit): Chat.AudioMsg =
  AudioMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

