// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chat.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.example.aaaaaac.proto.Chat

@kotlin.jvm.JvmName("-initializereqMsg")
public inline fun reqMsg(block: ReqMsgKt.Dsl.() -> kotlin.Unit): Chat.ReqMsg =
  ReqMsgKt.Dsl._create(Chat.ReqMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ReqMsg`
 */
public object ReqMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Chat.ReqMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Chat.ReqMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Chat.ReqMsg = _builder.build()

    /**
     * `.ReqMsg.Code code = 1;`
     */
    public var code: Chat.ReqMsg.Code
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    public var codeValue: kotlin.Int
      @JvmName("getCodeValue")
      get() = _builder.getCodeValue()
      @JvmName("setCodeValue")
      set(value) {
        _builder.setCodeValue(value)
      }
    /**
     * `.ReqMsg.Code code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `optional string extra = 2;`
     */
    public var extra: kotlin.String
      @JvmName("getExtra")
      get() = _builder.getExtra()
      @JvmName("setExtra")
      set(value) {
        _builder.setExtra(value)
      }
    /**
     * `optional string extra = 2;`
     */
    public fun clearExtra() {
      _builder.clearExtra()
    }
    /**
     * `optional string extra = 2;`
     * @return Whether the extra field is set.
     */
    public fun hasExtra(): kotlin.Boolean {
      return _builder.hasExtra()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Chat.ReqMsg.copy(block: ReqMsgKt.Dsl.() -> kotlin.Unit): Chat.ReqMsg =
  ReqMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

