// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chat.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.example.aaaaaac.proto.Chat

@kotlin.jvm.JvmName("-initializetextMsg")
public inline fun textMsg(block: TextMsgKt.Dsl.() -> kotlin.Unit): Chat.TextMsg =
  TextMsgKt.Dsl._create(Chat.TextMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `TextMsg`
 */
public object TextMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Chat.TextMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Chat.TextMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Chat.TextMsg = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Chat.TextMsg.copy(block: TextMsgKt.Dsl.() -> kotlin.Unit): Chat.TextMsg =
  TextMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

